# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\王永健\PCG\MinecraftLauncher\Ui\gamedownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameDownloader(object):
    def setupUi(self, GameDownloader):
        GameDownloader.setObjectName("GameDownloader")
        GameDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameDownloader)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(GameDownloader)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb_liteloader = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_liteloader.setObjectName("cb_liteloader")
        self.gridLayout_3.addWidget(self.cb_liteloader, 3, 1, 1, 1)
        self.cb_optifine = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_optifine.setObjectName("cb_optifine")
        self.gridLayout_3.addWidget(self.cb_optifine, 2, 1, 1, 1)
        self.cb_forge = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_forge.setObjectName("cb_forge")
        self.gridLayout_3.addWidget(self.cb_forge, 1, 1, 1, 1)
        self.cb_version = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_version.setObjectName("cb_version")
        self.gridLayout_3.addWidget(self.cb_version, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(GameDownloader)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_download = QtWidgets.QPushButton(self.groupBox)
        self.pb_download.setEnabled(False)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout_2.addWidget(self.pb_download, 0, 3, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(GameDownloader)
        QtCore.QMetaObject.connectSlotsByName(GameDownloader)

    def retranslateUi(self, GameDownloader):
        _translate = QtCore.QCoreApplication.translate
        GameDownloader.setWindowTitle(_translate("GameDownloader", "游戏下载器"))
        self.groupBox_2.setTitle(_translate("GameDownloader", "下载选择"))
        self.label_2.setText(_translate("GameDownloader", "版本"))
        self.label_3.setText(_translate("GameDownloader", "Forge"))
        self.label_4.setText(_translate("GameDownloader", "Optifine"))
        self.label_5.setText(_translate("GameDownloader", "Liteloader"))
        self.groupBox.setTitle(_translate("GameDownloader", "下载概况"))
        self.pb_download.setText(_translate("GameDownloader", "下载"))
        self.label.setText(_translate("GameDownloader", "名称"))
