# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\王永健\PCG\MinecraftLauncher\Ui\gamelauncher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameLauncher(object):
    def setupUi(self, GameLauncher):
        GameLauncher.setObjectName("GameLauncher")
        GameLauncher.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameLauncher)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_startgame = QtWidgets.QPushButton(GameLauncher)
        self.pb_startgame.setObjectName("pb_startgame")
        self.gridLayout.addWidget(self.pb_startgame, 2, 0, 1, 1)
        self.cb_curversion = QtWidgets.QComboBox(GameLauncher)
        self.cb_curversion.setObjectName("cb_curversion")
        self.gridLayout.addWidget(self.cb_curversion, 0, 0, 1, 1)
        self.le_playername = QtWidgets.QLineEdit(GameLauncher)
        self.le_playername.setObjectName("le_playername")
        self.gridLayout.addWidget(self.le_playername, 1, 0, 1, 1)

        self.retranslateUi(GameLauncher)
        QtCore.QMetaObject.connectSlotsByName(GameLauncher)

    def retranslateUi(self, GameLauncher):
        _translate = QtCore.QCoreApplication.translate
        GameLauncher.setWindowTitle(_translate("GameLauncher", "游戏启动器"))
        self.pb_startgame.setText(_translate("GameLauncher", "开始游戏"))
