# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\王永健\PCG\MinecraftLauncher\Ui\moddetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModDetail(object):
    def setupUi(self, ModDetail):
        ModDetail.setObjectName("ModDetail")
        ModDetail.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModDetail)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(ModDetail)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_describe = QtWidgets.QLabel(self.groupBox)
        self.l_describe.setText("")
        self.l_describe.setObjectName("l_describe")
        self.gridLayout_2.addWidget(self.l_describe, 1, 0, 1, 1)
        self.l_name = QtWidgets.QLabel(self.groupBox)
        self.l_name.setText("")
        self.l_name.setObjectName("l_name")
        self.gridLayout_2.addWidget(self.l_name, 0, 0, 1, 1)
        self.pb_mcmod = QtWidgets.QPushButton(self.groupBox)
        self.pb_mcmod.setObjectName("pb_mcmod")
        self.gridLayout_2.addWidget(self.pb_mcmod, 0, 1, 1, 1)
        self.pb_curseforge = QtWidgets.QPushButton(self.groupBox)
        self.pb_curseforge.setObjectName("pb_curseforge")
        self.gridLayout_2.addWidget(self.pb_curseforge, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.lw_modfiles = QtWidgets.QListWidget(ModDetail)
        self.lw_modfiles.setObjectName("lw_modfiles")
        self.gridLayout.addWidget(self.lw_modfiles, 1, 0, 1, 1)

        self.retranslateUi(ModDetail)
        QtCore.QMetaObject.connectSlotsByName(ModDetail)

    def retranslateUi(self, ModDetail):
        _translate = QtCore.QCoreApplication.translate
        ModDetail.setWindowTitle(_translate("ModDetail", "模组详情"))
        self.pb_mcmod.setText(_translate("ModDetail", "mcmod百科"))
        self.pb_curseforge.setText(_translate("ModDetail", "curseforge"))
