# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\王永健\PCG\MinecraftLauncher\Ui\moddownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModDownloader(object):
    def setupUi(self, ModDownloader):
        ModDownloader.setObjectName("ModDownloader")
        ModDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModDownloader)
        self.gridLayout.setObjectName("gridLayout")
        self.gb_search = QtWidgets.QGroupBox(ModDownloader)
        self.gb_search.setObjectName("gb_search")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_search)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_name = QtWidgets.QLabel(self.gb_search)
        self.l_name.setObjectName("l_name")
        self.gridLayout_2.addWidget(self.l_name, 0, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.gb_search)
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 1, 1, 1)
        self.pb_search = QtWidgets.QPushButton(self.gb_search)
        self.pb_search.setObjectName("pb_search")
        self.gridLayout_2.addWidget(self.pb_search, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.gb_search, 0, 0, 1, 1)
        self.lw_result = QtWidgets.QListWidget(ModDownloader)
        self.lw_result.setObjectName("lw_result")
        self.gridLayout.addWidget(self.lw_result, 1, 0, 1, 1)

        self.retranslateUi(ModDownloader)
        QtCore.QMetaObject.connectSlotsByName(ModDownloader)

    def retranslateUi(self, ModDownloader):
        _translate = QtCore.QCoreApplication.translate
        ModDownloader.setWindowTitle(_translate("ModDownloader", "模组下载器"))
        self.gb_search.setTitle(_translate("ModDownloader", "搜索"))
        self.l_name.setText(_translate("ModDownloader", "名称"))
        self.pb_search.setText(_translate("ModDownloader", "搜索"))
