# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\王永健\PCG\MinecraftLauncher\Ui\threadmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThreadManager(object):
    def setupUi(self, ThreadManager):
        ThreadManager.setObjectName("ThreadManager")
        ThreadManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ThreadManager)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_task = BaseListWidget(ThreadManager)
        self.lw_task.setObjectName("lw_task")
        self.gridLayout.addWidget(self.lw_task, 0, 0, 1, 1)

        self.retranslateUi(ThreadManager)
        QtCore.QMetaObject.connectSlotsByName(ThreadManager)

    def retranslateUi(self, ThreadManager):
        _translate = QtCore.QCoreApplication.translate
        ThreadManager.setWindowTitle(_translate("ThreadManager", "线程管理"))
from QtBase.baselistwidget import BaseListWidget
